In [1]:
import pandas as pd
import numpy as np

In [4]:
df_datafile1=pd.read_excel('teak working genes con_sorted_(2).xlsx') # GENEOMIC DATAS ARE preprocessed and missing values are sorted and transformed

In [3]:
import os
os.getcwd()

'C:\\Users\\SWARA LAKSHMI J\\PROJECT ML 1'

In [5]:
df_datafile1.head()

,Gene_ID,branch12yr_SRR2080148,branch12yr_SRR2080149,branch60yr_SRR2080150,branch60yr_SRR2080151,flowers_SRR2080094,leaves_SRR2080095,roots_SRR2080096,seedlings_SRR2080097,stem12yr_SRR2080131,stem12yr_SRR2080132,stem60yr_SRR2080137,stem60yr_SRR2080138
0,Tg01g00010,0.947526,0.214594,0.260706,0.146897,0.289305,1.17831,0.408811,0.221877,0.221030,0.230644,0.173426,0.257679
1,Tg01g00020,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,Tg01g00030,18.810400,17.392500,15.470800,16.664400,17.564600,10.99400,14.011400,20.792700,7.618540,3.355960,16.184200,12.528500
3,Tg01g00040,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Tg01g00050,2.498590,0.740532,0.618493,0.818552,1.356430,4.74561,3.009140,1.590730,0.845208,0.826855,0.851460,0.512924

In [7]:
#ROWS- SAMPLES
#COLUM- GENES 
df_transform=df_datafile1.set_index("Gene_ID").T

In [8]:
df_transform

Gene_ID,Tg01g00010,Tg01g00020,Tg01g00030,Tg01g00040,Tg01g00050,Tg01g00060,Tg01g00070,Tg01g00080,Tg01g00090,Tg01g00100,...,TgUn908g00020,TgUn909g00010,TgUn910g00010,TgUn910g00020,TgUn910g00030,TgUn912g00010,TgUn913g00010,TgUn913g00020,TgUn914g00010,TgUn916g00010
branch12yr_SRR2080148,0.947526,0.0,18.81040,0.0,2.498590,2.07545,1.428320,1.484620,0.359810,0.000000,...,0.043687,8.71863,11.09590,1.603030,0.397055,5.10498,1.853150,0.0,0.286351,0.000000
branch12yr_SRR2080149,0.214594,0.0,17.39250,0.0,0.740532,5.14670,0.648307,0.722430,0.000000,0.141313,...,0.499616,4.39834,2.07424,0.335920,0.000000,3.50482,1.823340,0.0,0.000000,0.000000
branch60yr_SRR2080150,0.260706,0.0,15.47080,0.0,0.618493,3.64701,0.376167,0.238669,0.000000,0.012716,...,0.607778,6.02040,5.21831,0.349097,0.000000,3.40542,1.669840,0.0,0.110734,0.000000
branch60yr_SRR2080151,0.146897,0.0,16.66440,0.0,0.818552,5.96584,0.597108,0.301012,0.000000,0.000000,...,0.659697,3.87519,7.55136,0.426738,0.000000,3.70971,1.616840,0.0,0.059319,0.000000
flowers_SRR2080094,0.289305,0.0,17.56460,0.0,1.356430,1.85571,20.883000,3.403480,1.703850,0.513416,...,0.000000,5.43186,22.10470,2.979790,0.121919,4.09966,1.025650,0.0,1.789000,0.000000
leaves_SRR2080095,1.178310,0.0,10.99400,0.0,4.745610,4.91937,11.734600,3.002440,1.324520,0.991280,...,0.038062,2.22377,23.80290,1.490590,0.000000,3.82658,1.320110,0.0,7.206370,0.156331
roots_SRR2080096,0.408811,0.0,14.01140,0.0,3.009140,3.43633,8.041130,4.931450,0.463413,0.129238,...,0.183353,4.09314,15.66750,1.976170,0.000000,1.85271,1.829470,0.0,10.427100,0.129842
seedlings_SRR2080097,0.221877,0.0,20.79270,0.0,1.590730,2.32323,6.657990,6.077560,1.004540,0.155597,...,0.061899,2.49901,14.80400,1.903150,0.000000,1.10754,0.812059,0.0,5.149590,0.000000
stem12yr_SRR2080131,0.221030,0.0,7.61854,0.0,0.845208,15.74650,0.762326,0.117941,0.000000,0.000000,...,0.150037,2.46304,2.60536,0.805027,0.000000,7.65384,1.820700,0.0,0.060084,0.000000
stem12yr_SRR2080132,0.230644,0.0,3.35596,0.0,0.826855,14.51780,1.497280,0.170935,0.000000,0.000000,...,0.322117,4.28482,2.92890,0.525016,0.000000,7.71369,1.382520,0.0,0.000000,0.000000
stem60yr_SRR2080137,0.173426,0.0,16.18420,0.0,0.851460,4.47227,1.029990,0.068462,0.000000,0.000000,...,0.759972,5.14528,3.46673,0.657316,0.000000,5.33737,1.826350,0.0,0.000000,0.000000
stem60yr_SRR2080138,0.257679,0.0,12.52850,0.0,0.512924,5.23645,0.565153,0.211303,0.000000,0.000000,...,0.423112,2.01889,4.31491,0.361256,0.000000,4.99931,1.647660,0.0,0.000000,0.000000

In [13]:
df_transform.isnull().sum().sum()

12

In [16]:
df_transform.isnull().sum()[df_transform.isnull().sum()>0]

Gene_ID
Tissue    12
dtype: int64

In [30]:
df_transform.head()

Gene_ID,Tg01g00010,Tg01g00020,Tg01g00030,Tg01g00040,Tg01g00050,Tg01g00060,Tg01g00070,Tg01g00080,Tg01g00090,Tg01g00100,...,TgUn910g00010,TgUn910g00020,TgUn910g00030,TgUn912g00010,TgUn913g00010,TgUn913g00020,TgUn914g00010,TgUn916g00010,Tissue,Gene_ID
branch12yr_SRR2080148,0.947526,0.0,18.8104,0.0,2.498590,2.07545,1.428320,1.484620,0.35981,0.000000,...,11.09590,1.603030,0.397055,5.10498,1.85315,0.0,0.286351,0.0,NaN,NaN
branch12yr_SRR2080149,0.214594,0.0,17.3925,0.0,0.740532,5.14670,0.648307,0.722430,0.00000,0.141313,...,2.07424,0.335920,0.000000,3.50482,1.82334,0.0,0.000000,0.0,NaN,NaN
branch60yr_SRR2080150,0.260706,0.0,15.4708,0.0,0.618493,3.64701,0.376167,0.238669,0.00000,0.012716,...,5.21831,0.349097,0.000000,3.40542,1.66984,0.0,0.110734,0.0,NaN,NaN
branch60yr_SRR2080151,0.146897,0.0,16.6644,0.0,0.818552,5.96584,0.597108,0.301012,0.00000,0.000000,...,7.55136,0.426738,0.000000,3.70971,1.61684,0.0,0.059319,0.0,NaN,NaN
flowers_SRR2080094,0.289305,0.0,17.5646,0.0,1.356430,1.85571,20.883000,3.403480,1.70385,0.513416,...,22.10470,2.979790,0.121919,4.09966,1.02565,0.0,1.789000,0.0,NaN,NaN

In [31]:
df_transform=df_transform.drop(columns=['Gene_ID','Tissue'])

In [32]:
df_transform.head()

Gene_ID,Tg01g00010,Tg01g00020,Tg01g00030,Tg01g00040,Tg01g00050,Tg01g00060,Tg01g00070,Tg01g00080,Tg01g00090,Tg01g00100,...,TgUn908g00020,TgUn909g00010,TgUn910g00010,TgUn910g00020,TgUn910g00030,TgUn912g00010,TgUn913g00010,TgUn913g00020,TgUn914g00010,TgUn916g00010
branch12yr_SRR2080148,0.947526,0.0,18.8104,0.0,2.498590,2.07545,1.428320,1.484620,0.35981,0.000000,...,0.043687,8.71863,11.09590,1.603030,0.397055,5.10498,1.85315,0.0,0.286351,0.0
branch12yr_SRR2080149,0.214594,0.0,17.3925,0.0,0.740532,5.14670,0.648307,0.722430,0.00000,0.141313,...,0.499616,4.39834,2.07424,0.335920,0.000000,3.50482,1.82334,0.0,0.000000,0.0
branch60yr_SRR2080150,0.260706,0.0,15.4708,0.0,0.618493,3.64701,0.376167,0.238669,0.00000,0.012716,...,0.607778,6.02040,5.21831,0.349097,0.000000,3.40542,1.66984,0.0,0.110734,0.0
branch60yr_SRR2080151,0.146897,0.0,16.6644,0.0,0.818552,5.96584,0.597108,0.301012,0.00000,0.000000,...,0.659697,3.87519,7.55136,0.426738,0.000000,3.70971,1.61684,0.0,0.059319,0.0
flowers_SRR2080094,0.289305,0.0,17.5646,0.0,1.356430,1.85571,20.883000,3.403480,1.70385,0.513416,...,0.000000,5.43186,22.10470,2.979790,0.121919,4.09966,1.02565,0.0,1.789000,0.0

In [34]:
df_transform.isnull().sum()[df_transform.isnull().sum()>0]

Series([], dtype: int64)

In [35]:
df_transform.isnull().sum().sum()

0